<html> 
    <head> 
        <link rel="stylesheet" type="text/css" media="screen" href="/css/main.css" /> 
        <script type="text/javascript" src="/js/site.js"></script> 
        <title>Online Book Store</title> 
    </head>
    <body> 
        <nav> 


            <table> 
                <tr> 
                    <td valign="top">  
                        <table width="700"> 
                            <tr valign="bottom"> 
                                <td class="value"><a href="/"><img src="/images/logo.jpg" border="0"  width="180"></a></td> 
                                <td class="value"><a href="/books"><img src="/images/home.png" border="0"  width="55"></a></td> 
                                <td class="value"><a href="./signup"> <img src="/images/register.png" border="0"  width="55"></a></td> 
                                <td class="value"><a href="/books"><img src="/images/cart.png" border="0"  width="55"></a></td> 
                                <td class="value"><a href="/books"><img src="/images/login.png" border="0"  width="55"></a></td> 
                                <td class="value"><a href="/contact"><img src="/images/admin.png" border="0"  width="55"></a></td> 
                            </tr> 
                        </table> 
                    </td> 
                </tr> 
            </table> 

            




</nav>